// Command ib is a small rebrandable CLI shell that composes a generated devedge
// domain command module over the clikit runtime. It is the CLI mirror of a
// devedge-ufe-sdk example shell: the shell owns session construction (binding
// the generic OIDC device-grant provider, or a --dev stub), and the generated
// widgets module consumes only the read-only runtime.
//
// The widgets module under gen/widgets is generated by cligen from
// testdata/toy.openapi.yaml and committed so this example builds as-is.
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/infobloxopen/devedge-cli-sdk/clikit"
	"github.com/infobloxopen/devedge-cli-sdk/clikit/auth"
	"github.com/infobloxopen/devedge-cli-sdk/clikit/auth/oidc"
	widgets "github.com/infobloxopen/devedge-cli-sdk/examples/ib/gen/widgets"
)

const appName = "ib"

// newApp builds the ib shell. It is shared by main and the e2e test.
func newApp() *clikit.App {
	app := clikit.NewApp(appName)

	// The shell owns session construction. It binds the generic OIDC
	// device-grant provider from the active profile; --dev bypasses this with a
	// static stub token. A private preset overlay would supply concrete
	// issuer/client values without changing this seam.
	app.SetSessionFactory(func(p clikit.Profile) (auth.Session, error) {
		if p.Auth.OIDC.ClientID == "" && p.Auth.OIDC.Issuer == "" {
			return nil, fmt.Errorf("profile %q has no oidc config; use --dev for local development", p.Name)
		}
		return oidc.New(oidc.Config{
			Issuer:   p.Auth.OIDC.Issuer,
			ClientID: p.Auth.OIDC.ClientID,
			Scopes:   p.Auth.OIDC.Scopes,
			Audience: p.Auth.OIDC.Audience,
			Store:    &auth.FileStore{Path: filepath.Join(clikit.ConfigDir(appName), "token.json")},
		}), nil
	})

	root := app.Root()
	root.AddCommand(widgets.Command(app.Runtime()))
	root.AddCommand(clikit.NewDoctorCommand(appName))
	return app
}

func main() {
	if err := newApp().Execute(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
